#!/usr/bin/env node
// Builds the web app into build/www (used by GitHub Pages AND by the iOS/Android shells).
//   node scripts/build.mjs          → build/www
//   node scripts/build.mjs --site   → also build/site (www + update.json + updates/app-<version>.zip)
//
// Version = <major>.<minor> from package.json + number of git commits, so every push to
// main gets a higher version and Pages + native builds of the same commit agree.
import { execSync } from 'node:child_process';
import { createHash } from 'node:crypto';
import fs from 'node:fs';
import path from 'node:path';
import { fileURLToPath } from 'node:url';

const root = path.resolve(path.dirname(fileURLToPath(import.meta.url)), '..');
const out = path.join(root, 'build', 'www');
const site = path.join(root, 'build', 'site');
const nm = path.join(root, 'node_modules');
const args = new Set(process.argv.slice(2));

const pkg = JSON.parse(fs.readFileSync(path.join(root, 'package.json'), 'utf8'));

function sh(cmd) { try { return execSync(cmd, { cwd: root, stdio: ['ignore', 'pipe', 'ignore'] }).toString().trim(); } catch { return ''; } }

// ---------- version ----------
const [major = 1, minor = 0] = pkg.version.split('.');
const commits = sh('git rev-list --count HEAD') || process.env.GITHUB_RUN_NUMBER || '0';
const version = `${major}.${minor}.${commits}`;
const buildTime = new Date().toISOString();

// ---------- where updates are published ----------
function pagesUrl() {
  if (process.env.PAGES_URL) return process.env.PAGES_URL.replace(/\/?$/, '/');
  const repo = process.env.GITHUB_REPOSITORY || sh('git config --get remote.origin.url').replace(/^.*github\.com[:/]/, '').replace(/\.git$/, '');
  if (!repo || !repo.includes('/')) return '';
  const [owner, name] = repo.split('/');
  const host = `https://${owner.toLowerCase()}.github.io/`;
  return name.toLowerCase() === `${owner.toLowerCase()}.github.io` ? host : `${host}${name}/`;
}
const base = pagesUrl();
const manifestUrl = base ? `${base}update.json` : '';

// ---------- copy app ----------
fs.rmSync(path.join(root, 'build'), { recursive: true, force: true });
fs.cpSync(path.join(root, 'www'), out, { recursive: true });

// ---------- vendor libraries (from node_modules) ----------
function pick(pkgName, candidates) {
  for (const c of candidates) {
    const p = path.join(nm, pkgName, c);
    if (fs.existsSync(p)) return p;
  }
  const dir = path.join(nm, pkgName);
  throw new Error(`Could not find ${candidates.join(' or ')} in ${pkgName}.\n` +
    (fs.existsSync(dir) ? `Contents of ${dir}/dist: ${fs.readdirSync(path.join(dir, 'dist')).join(', ')}` : `Run "npm install" first.`));
}
const vendor = path.join(out, 'vendor');
fs.mkdirSync(vendor, { recursive: true });
const copies = [
  [pick('@ffmpeg/ffmpeg', ['dist/esm']), 'ffmpeg'],
  [pick('@ffmpeg/core', ['dist/esm/ffmpeg-core.js']), 'ffmpeg-core/ffmpeg-core.js'],
  [pick('@ffmpeg/core', ['dist/esm/ffmpeg-core.wasm']), 'ffmpeg-core/ffmpeg-core.wasm'],
  [pick('heic2any', ['dist/heic2any.min.js', 'dist/heic2any.js']), 'heic2any.min.js'],
  [pick('@capacitor/core', ['dist/capacitor.js']), 'capacitor.js'],
];
for (const [from, to] of copies) {
  const dest = path.join(vendor, to);
  fs.mkdirSync(path.dirname(dest), { recursive: true });
  fs.cpSync(from, dest, { recursive: true });
}

function walk(dir, rel = '') {
  return fs.readdirSync(dir, { withFileTypes: true }).flatMap(d =>
    d.isDirectory() ? walk(path.join(dir, d.name), `${rel}${d.name}/`) : [`${rel}${d.name}`]);
}
const vendorFiles = walk(vendor).filter(f => !f.endsWith('.map') && !f.endsWith('.d.ts'));
const vendorId = createHash('sha1').update(vendorFiles.map(f => `${f}:${fs.statSync(path.join(vendor, f)).size}`).join('|')).digest('hex').slice(0, 10);
fs.writeFileSync(path.join(vendor, 'manifest.json'), JSON.stringify({ id: vendorId, files: vendorFiles.filter(f => f !== 'capacitor.js').map(f => `vendor/${f}`) }, null, 2));

// ---------- config + version files ----------
fs.writeFileSync(path.join(out, 'js', 'config.js'),
  `// Generated by scripts/build.mjs\nexport const APP_VERSION = ${JSON.stringify(version)};\nexport const BUILD_TIME = ${JSON.stringify(buildTime)};\nexport const UPDATE_MANIFEST_URL = ${JSON.stringify(manifestUrl)};\n`);
fs.writeFileSync(path.join(out, 'version.json'), JSON.stringify({ version, buildTime }, null, 2));

// ---------- stamp the service worker ----------
const shell = ['./', ...walk(out).filter(f => !f.startsWith('vendor/') && f !== 'sw.js' && f !== 'version.json' && !f.startsWith('icons/maskable')).map(f => `./${f}`)];
let sw = fs.readFileSync(path.join(out, 'sw.js'), 'utf8');
sw = sw.replace(/const VERSION = '.*?';/, `const VERSION = ${JSON.stringify(version)};`)
  .replace(/const VENDOR_ID = '.*?';/, `const VENDOR_ID = ${JSON.stringify(vendorId)};`)
  .replace(/const SHELL = \[[\s\S]*?\];/, `const SHELL = ${JSON.stringify(shell, null, 2)};`);
fs.writeFileSync(path.join(out, 'sw.js'), sw);

console.log(`Built ${version} → build/www (${vendorFiles.length} vendor files, update manifest: ${manifestUrl || 'none (local build)'})`);

// ---------- Pages site with the self-update bundle ----------
if (args.has('--site')) {
  if (!base) throw new Error('Cannot work out the GitHub Pages URL. Set PAGES_URL or run inside GitHub Actions.');
  fs.cpSync(out, site, { recursive: true });
  const zipName = `app-${version}.zip`;
  fs.mkdirSync(path.join(site, 'updates'), { recursive: true });
  execSync(`zip -qr -X "${path.join(site, 'updates', zipName)}" .`, { cwd: out, stdio: 'inherit' });
  const zipPath = path.join(site, 'updates', zipName);
  const update = {
    version,
    url: `${base}updates/${zipName}`,
    size: fs.statSync(zipPath).size,
    buildTime,
  };
  fs.writeFileSync(path.join(site, 'update.json'), JSON.stringify(update, null, 2));
  fs.writeFileSync(path.join(site, '.nojekyll'), '');
  console.log(`Site ready → build/site (bundle ${(update.size / 1048576).toFixed(1)} MB)`);
}
